const fs = require('fs');

let wd = fs.readFileSync('src/components/WhatsAppDashboard.tsx', 'utf8');

// 1. Add import for MobileVoiceEditor
if (!wd.includes('MobileVoiceEditor')) {
    wd = wd.replace("import VoiceAssetsTab from './VoiceAssetsTab';", "import VoiceAssetsTab from './VoiceAssetsTab';\nimport MobileVoiceEditor from './MobileVoiceEditor';");
}

// 2. Add 'add-product-voice-transcribe' state
if (!wd.includes('const [transcriptionText, setTranscriptionText] = useState')) {
    wd = wd.replace('const [audioBlob, setAudioBlob] = useState<Blob | null>(null);', 'const [audioBlob, setAudioBlob] = useState<Blob | null>(null);\n    const [transcriptionText, setTranscriptionText] = useState("");');
}

// 3. Add Transcribe button below Advanced Edit
const advancedEditBtn = `<button 
                                        onClick={() => setActiveMobilePage('add-product-voice-edit')}
                                        className="bg-indigo-600 text-white w-full py-4 rounded-full font-bold shadow-lg active:scale-95 transition-all text-lg flex items-center justify-center gap-2 mb-4"
                                    >
                                        <Edit3 size={20} /> Advanced Edit
                                    </button>`;

const newButtons = `<button 
                                        onClick={() => setActiveMobilePage('add-product-voice-edit')}
                                        className="bg-indigo-600 text-white w-full py-4 rounded-full font-bold shadow-lg shadow-indigo-900/30 active:scale-95 transition-all text-lg flex items-center justify-center gap-2 mb-3"
                                    >
                                        <Edit3 size={20} /> Advanced Edit
                                    </button>
                                    <button 
                                        onClick={() => {
                                            setTranscriptionText("This is an auto-generated mock transcription of the voice note. In a real environment, this would be generated by Whisper API or similar.");
                                            setActiveMobilePage('add-product-voice-transcribe');
                                        }}
                                        className="bg-[#18181b] border border-white/10 text-white w-full py-4 rounded-full font-bold shadow-lg active:scale-95 transition-all text-lg flex items-center justify-center gap-2 mb-4"
                                    >
                                        <FileText size={20} className="text-emerald-400" /> Transcribe Voice
                                    </button>`;
if (wd.includes(advancedEditBtn)) {
    wd = wd.replace(advancedEditBtn, newButtons);
} else {
    // try looser match
    wd = wd.replace(/<button[^>]*onClick=\{\(\) => setActiveMobilePage\('add-product-voice-edit'\)\}[^>]*>[\s\S]*?<\/button>/, newButtons);
}

// 4. Replace the VoiceAssetsTab modal for voice-edit with MobileVoiceEditor
const oldEditModal = `{activeMobilePage === 'add-product-voice-edit' && (
                    <div className="flex flex-col h-full w-full absolute inset-0 bg-[#030712] z-[90] animate-in slide-in-from-right duration-200">
                        <div className="h-14 bg-[#09090b] border-b border-white/5 flex items-center px-4 shrink-0 shadow-sm relative z-50">
                            <button onClick={() => setActiveMobilePage('add-product-voice')} className="absolute left-4 p-2 -m-2 text-indigo-400 active:opacity-50 flex items-center gap-1 z-10">
                                <ChevronLeft size={24} /> <span className="text-base font-semibold">Cancel</span>
                            </button>
                        </div>
                        <div className="flex-1 overflow-hidden relative">
                            <VoiceAssetsTab category="policy" title="Product Voice Editor" description="" standaloneMode={true} standaloneBlob={audioBlob} onStandaloneSave={(blob) => { setAudioBlob(blob); setAudioPreviewUrl(URL.createObjectURL(blob)); setActiveMobilePage('add-product-voice'); }} />
                        </div>
                    </div>
                )}`;

const newEditModal = `{activeMobilePage === 'add-product-voice-edit' && (
                    <MobileVoiceEditor 
                        audioBlob={audioBlob} 
                        onCancel={() => setActiveMobilePage('add-product-voice')} 
                        onSave={(blob) => { setAudioBlob(blob); setAudioPreviewUrl(URL.createObjectURL(blob)); setActiveMobilePage('add-product-voice'); }} 
                    />
                )}

                {activeMobilePage === 'add-product-voice-transcribe' && (
                    <div className="flex flex-col h-full w-full absolute inset-0 bg-[#030712] z-[100] animate-in slide-in-from-bottom-2 duration-200">
                        <div className="h-14 bg-[#09090b] border-b border-white/5 flex items-center px-4 shrink-0 shadow-sm relative">
                            <button onClick={() => setActiveMobilePage('add-product-voice')} className="absolute left-4 p-2 -m-2 text-emerald-400 active:opacity-50 flex items-center gap-1 z-10">
                                <ChevronLeft size={24} /> <span className="text-base font-semibold">Back</span>
                            </button>
                            <h1 className="text-lg font-bold text-white w-full text-center">Transcription</h1>
                            <button onClick={() => setActiveMobilePage('add-product-voice')} className="absolute right-4 p-2 -m-2 text-indigo-400 font-bold active:opacity-50">
                                Save
                            </button>
                        </div>
                        <div className="flex-1 overflow-y-auto p-4 flex flex-col items-center">
                            <div className="w-20 h-20 bg-emerald-500/10 rounded-full flex items-center justify-center mb-6 shadow-xl shadow-emerald-900/20">
                                <FileText size={40} className="text-emerald-400" />
                            </div>
                            <h2 className="text-xl font-bold text-white mb-2">Voice to Text</h2>
                            <p className="text-sm text-zinc-500 mb-8 text-center px-4">Your voice note has been automatically transcribed. You can edit the text below.</p>
                            
                            <div className="w-full bg-[#18181b] rounded-3xl p-1 border border-white/10 shadow-inner relative group">
                                <textarea 
                                    value={transcriptionText} 
                                    onChange={e => setTranscriptionText(e.target.value)}
                                    className="w-full h-64 bg-transparent text-white text-lg p-5 outline-none resize-none leading-relaxed font-medium"
                                    placeholder="Transcription will appear here..."
                                />
                                <div className="absolute top-4 right-4 opacity-30 group-focus-within:opacity-100 transition-opacity">
                                    <Edit3 size={20} className="text-indigo-400" />
                                </div>
                            </div>
                            <p className="text-xs text-zinc-600 mt-4 font-semibold uppercase tracking-widest flex items-center gap-1">
                                <CheckCircle size={12} className="text-emerald-500" /> Auto-saving enabled
                            </p>
                        </div>
                    </div>
                )}`;

if (wd.includes(oldEditModal)) {
    wd = wd.replace(oldEditModal, newEditModal);
} else {
    console.log("Could not find oldEditModal!");
    // manual replace logic just in case whitespace changed
    wd = wd.replace(/\{activeMobilePage === 'add-product-voice-edit' && \([\s\S]*?<\/div>\s*\)\}/, newEditModal);
}

fs.writeFileSync('src/components/WhatsAppDashboard.tsx', wd);
console.log('Done integrating MobileVoiceEditor and Transcribe');
